### ISSUE TITLE
Library doesn't work with current Signal Desktop

### ISSUE THREAD

**Issue by selfbc** [signal-golang/textsecure#13] opened 2020-04-06 10:37 UTC
Looks like due to envelope timestamps, the messages from this library don't show up with Signal Desktop version 1.32.0 and above.  I tested with the CLI client to confirm.  I can give more information from Signal Desktop commits if needed.

**Comment by nanu-c** [comment] 2020-04-06 12:33
I think it's a duplicate of https://github.com/nanu-c/axolotl/issues/110

**Comment by nanu-c** [comment] 2020-04-06 12:34
i would love it if you find the reason. I thought that textsecure isn't sending to messages to the linked devices and signal server doesn't forward it.

**Comment by selfbc** [comment] 2020-04-06 15:42
If this helps, it's from this commit: signalapp/Signal-Desktop@7ca0dfd#diff-0b3c72f8fa053c9f175d037847bb9b32R124

I can give more information as needed.

**Comment by morph027** [comment] 2020-04-06 15:50
noticed this too this week:

```
signal[181]: time="2020/04/06 17:47:24" level=debug msg="[textsecure] SendMessageResponse: {NeedsSync:false Timestamp:1586188043845}\n"
```

**Comment by selfbc** [comment] 2020-04-06 15:51
Yes, the library no longer works with Signal Desktop as of 1.32.0 due to these changes.

**Comment by nanu-c** [comment] 2020-04-06 17:16
timestamp is currently set here
https://github.com/signal-golang/textsecure/blob/306535efb3d80b9a5d4b973e269b6c644cdaf118/server.go#L705
and doesn't respect the envelope timestamp. We have to rebuild the message with the correct timestamp

**Comment by selfbc** [comment] 2020-04-07 02:32
Looks like the API document hasn't been updated since 2014 - https://github.com/signalapp/Signal-Server/wiki/API-Protocol

**Comment by WanderingGlitch** [comment] 2020-04-07 04:56
For what it's worth, modifying the check at https://github.com/signalapp/Signal-Desktop/blob/37ad95af2735f18ed33e9cc5808adae05d542bba/libtextsecure/message_receiver.js#L1378 shows that the envelope does have a timestamp but that the decrypted message does not.

Additionally, commenting out these lines in Signal Desktop allows messages to be received (including the queued ones that haven't been successfully processed): https://github.com/signalapp/Signal-Desktop/blob/37ad95af2735f18ed33e9cc5808adae05d542bba/libtextsecure/message_receiver.js#L1378-L1389

From what I can tell, `createMessage` needs to set the timestamp in the DataMessage and `buildAndSendMessage` needs to use the same value

**Comment by nanu-c** [comment] 2020-04-07 09:15
Will do that later that week, maybe this evening :)

**Comment by nanu-c** [comment] 2020-04-07 23:33
fixed in 6c66a38d5a81341d189e0425698ab022501189c1

**Closed by nanu-c** 2020-04-07 23:33 UTC

**Comment by morph027** [comment] 2020-04-08 04:18
Jip, confirmed working, thank you! :heart:

**Comment by selfbc** [comment] 2020-04-08 06:52
Everything is going good on my end.  Thanks for the speedy work!

**Comment by nanu-c** [comment] 2020-04-08 07:50
We can continue to solve the remaining problems that way. If someone does the research in the original signal sources, then it's way more easy for me to provide a solution
